In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('algerian_forest.csv')

In [7]:
df.head()

Temperature  RH  Ws  Rain  FFMC  DMC    DC  ISI   BUI  FWI  Classes  Region
0           26  82  22  13.1  47.1  2.5   7.1  0.3   2.7  0.1        0       0
1           25  89  13   2.5  28.6  1.3   6.9  0.0   1.7  0.0        0       0
2           27  77  16   0.0  64.8  3.0  14.2  1.2   3.9  0.5        0       0
3           31  67  14   0.0  82.6  5.8  22.2  3.1   7.0  2.5        1       0
4           33  54  13   0.0  88.2  9.9  30.5  6.4  10.9  7.2        1       0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Temperature  241 non-null    int64  
 1   RH           241 non-null    int64  
 2   Ws           241 non-null    int64  
 3   Rain         241 non-null    float64
 4   FFMC         241 non-null    float64
 5   DMC          241 non-null    float64
 6   DC           241 non-null    float64
 7   ISI          241 non-null    float64
 8   BUI          241 non-null    float64
 9   FWI          241 non-null    float64
 10  Classes      241 non-null    int64  
 11  Region       241 non-null    int64  
dtypes: float64(7), int64(5)
memory usage: 22.7 KB


In [11]:
#Independent and Dependent Features
x = df.drop('FWI', axis = 1)

In [13]:
x.head()

Temperature  RH  Ws  Rain  FFMC  DMC    DC  ISI   BUI  Classes  Region
0           26  82  22  13.1  47.1  2.5   7.1  0.3   2.7        0       0
1           25  89  13   2.5  28.6  1.3   6.9  0.0   1.7        0       0
2           27  77  16   0.0  64.8  3.0  14.2  1.2   3.9        0       0
3           31  67  14   0.0  82.6  5.8  22.2  3.1   7.0        1       0
4           33  54  13   0.0  88.2  9.9  30.5  6.4  10.9        1       0

In [15]:
y = df['FWI']

In [17]:
y.head()

0    0.1
1    0.0
2    0.5
3    2.5
4    7.2
Name: FWI, dtype: float64

In [19]:
#Train_test_split
from sklearn.model_selection import train_test_split

In [23]:
x_train,x_test,y_train,y_test = train_test_split (x,y,test_size = 0.25, random_state = 10)

In [27]:
x_train.shape

(180, 11)

In [29]:
x_test.shape

(61, 11)

In [31]:
y_train.shape

(180,)

In [35]:
y_test.shape

(61,)

In [37]:
x_train.corr()

Temperature        RH        Ws      Rain      FFMC       DMC  \
Temperature     1.000000 -0.624269 -0.226437 -0.281160  0.647794  0.463811   
RH             -0.624269  1.000000  0.265205  0.203924 -0.626697 -0.400566   
Ws             -0.226437  0.265205  1.000000  0.131867 -0.156879 -0.000460   
Rain           -0.281160  0.203924  0.131867  1.000000 -0.537508 -0.270897   
FFMC            0.647794 -0.626697 -0.156879 -0.537508  1.000000  0.596497   
DMC             0.463811 -0.400566 -0.000460 -0.270897  0.596497  1.000000   
DC              0.371996 -0.239325  0.088503 -0.291492  0.521303  0.881098   
ISI             0.590896 -0.691094 -0.015679 -0.336285  0.745557  0.684145   
BUI             0.443088 -0.351063  0.036127 -0.285694  0.593246  0.982568   
Classes         0.512284 -0.440674 -0.090899 -0.366166  0.786461  0.577943   
Region          0.244468 -0.410088 -0.180572 -0.043198  0.220270  0.193245   

                   DC       ISI       BUI   Classes    Region  
Temperature  0.371996  0.590896  0.443088  0.512284  0.244468  
RH          -0.239325 -0.691094 -0.351063 -0.440674 -0.410088  
Ws           0.088503 -0.015679  0.036127 -0.090899 -0.180572  
Rain        -0.291492 -0.336285 -0.285694 -0.366166 -0.043198  
FFMC         0.521303  0.745557  0.593246  0.786461  0.220270  
DMC          0.881098  0.684145  0.982568  0.577943  0.193245  
DC           1.000000  0.544145  0.942444  0.510999 -0.089938  
ISI          0.544145  1.000000  0.660582  0.726456  0.237224  
BUI          0.942444  0.660582  1.000000  0.586588  0.085975  
Classes      0.510999  0.726456  0.586588  1.000000  0.156957  
Region      -0.089938  0.237224  0.085975  0.156957  1.000000

In [45]:
def correlation(dataset, threshold):
    col_corr = set()
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i,j])>threshold:
                colname = corr_matrix.columns[i]
                col_corr.add(colname)

    return col_corr

In [49]:
corr_features = correlation(x_train, 0.85)

In [51]:
corr_features

{'BUI', 'DC'}

In [53]:
x_train.drop(corr_features,axis = 1, inplace = True)
x_test.drop(corr_features, axis = 1, inplace = True)

In [57]:
x_train.shape

(180, 9)

In [59]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler

In [61]:
scaler = StandardScaler()

In [63]:
scaler

StandardScaler()

In [69]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [71]:
x_train_scaled

array([[ 0.0247563 ,  0.64857356, -0.18454016, ...,  0.26995373,
         0.87447463, -1.        ],
       [ 0.86028128, -0.31454098,  0.52980884, ...,  0.79867139,
         0.87447463, -1.        ],
       [-1.92480201,  1.68048199, -0.89888915, ..., -1.03925192,
        -1.14354375, -1.        ],
       ...,
       [ 1.13878961, -2.10318226, -0.89888915, ...,  1.1259728 ,
         0.87447463,  1.        ],
       [ 0.86028128, -0.65851046, -1.61323814, ..., -0.35947206,
         0.87447463,  1.        ],
       [-1.64629368,  1.19892472,  1.24415783, ...,  0.06853747,
         0.87447463, -1.        ]])

In [73]:
x_test_scaled

array([[ 0.86028128, -0.24574708, -0.18454016, -0.37283886,  0.80929869,
         2.34287983,  0.92455655,  0.87447463, -1.        ],
       [ 1.13878961, -0.65851046,  0.88698333, -0.37283886,  0.84452303,
         0.44224452,  1.30221202,  0.87447463, -1.        ],
       [ 0.86028128, -0.0393654 , -0.54171465, -0.23398853, -0.05721998,
        -0.69495568, -0.7119505 , -1.14354375, -1.        ],
       [ 2.25282293, -2.03438837, -0.54171465, -0.37283886,  1.11927285,
        -0.28938078,  2.33447032,  0.87447463,  1.        ],
       [-0.25375203, -0.79609825, -0.54171465, -0.37283886,  0.72476029,
        -0.63928854,  0.42101592,  0.87447463, -1.        ],
       [ 0.30326463,  0.0982224 , -0.18454016, -0.32655542,  0.28093365,
        -0.17009405, -0.43500316,  0.87447463, -1.        ],
       [ 1.41729794, -1.89680058, -0.89888915, -0.09513819,  0.61908728,
         0.2752431 ,  0.06853747,  0.87447463,  1.        ],
       [-0.53226036, -0.65851046, -0.54171465,  1.06194793, -0

In [75]:
x_train

Temperature  RH  Ws  Rain  FFMC   DMC  ISI  Classes  Region
56            32  73  15   0.0  86.6  26.7  5.6        1       0
46            35  59  17   0.0  88.1  12.0  7.7        1       0
6             25  88  13   0.2  52.9   7.9  0.4        0       0
178           36  56  16   0.0  88.9  23.8  8.2        1       1
52            31  65  18   0.0  84.3  12.5  4.8        1       0
..           ...  ..  ..   ...   ...   ...  ...      ...     ...
64            32  75  14   0.0  86.4  13.0  5.2        1       0
15            31  78  14   0.3  56.9   1.9  0.7        0       0
228           36  33  13   0.1  90.6  25.8  9.0        1       1
125           35  54  11   0.1  83.7   8.4  3.1        1       1
9             26  81  19   0.0  84.0  13.8  4.8        1       0

[180 rows x 9 columns]

In [79]:
#Train the model
from sklearn.linear_model import LinearRegression

In [83]:
linreg = LinearRegression()

In [85]:
linreg.fit(x_train_scaled,y_train)

LinearRegression()

In [87]:
y_pred = linreg.predict(x_test_scaled)

In [89]:
y_pred

array([ 1.91445482e+01,  1.44761920e+01,  1.01805189e+00,  1.57920315e+01,
        6.79186117e+00,  4.63921727e+00,  7.69873214e+00,  1.64087142e+00,
        1.84349311e+00,  1.72353876e+00,  4.59840908e+00, -1.02954783e+00,
        6.25267815e+00, -1.05540061e+00,  6.43884002e-01,  4.36865178e-01,
        1.25361744e+00,  2.92731410e+01,  1.73398072e+01,  1.05650831e+01,
        2.13239135e+01,  2.15204954e+01,  5.12115057e+00,  1.08519979e+01,
        8.22188376e+00,  1.18526971e+01, -9.41758233e-01,  6.72301574e+00,
        2.28611318e+01,  1.28524018e+00,  4.10102288e+00,  1.43943707e+01,
        4.53511545e+00,  2.11331845e+00, -1.92548346e-01,  1.76683791e+01,
        6.64031207e+00,  1.07387296e+01,  1.31366961e+01, -1.30298750e-01,
        1.17142569e+01,  1.43394549e+01,  1.13563890e+01,  2.71090792e+01,
        9.98315801e+00,  1.02935841e+00,  4.23074035e+00,  2.76790041e+00,
        7.44970723e+00,  1.34103188e+00, -1.72342949e-02,  1.78543070e+01,
        1.68623876e+01,  

In [91]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [95]:
mae = mean_absolute_error(y_test,y_pred)

In [97]:
mae

0.7351686868037741

In [99]:
from sklearn.metrics import r2_score

In [105]:
score = r2_score(y_test, y_pred)

In [107]:
score

0.9845144141746723

Lasso Regression

In [112]:
from sklearn.linear_model import Lasso

In [114]:
lasso = Lasso()

In [116]:
lasso.fit(x_train_scaled, y_train)

Lasso()

In [118]:
y_pred = lasso.predict(x_test_scaled)

In [120]:
y_pred

array([16.61429997, 12.88111046,  2.10700088, 14.82530344,  6.5779316 ,
        4.59138537,  7.72321056,  2.87020221,  3.05276667,  2.5060087 ,
        4.87745736,  0.35852382,  6.31352247, -0.46772115,  2.31403446,
        2.26792101,  2.20016321, 25.5702668 , 15.81628432, 10.09841942,
       19.28966769, 19.45245866,  5.33576714, 10.46541919,  7.70626185,
       11.44412846,  0.40181249,  6.6353442 , 20.25805029,  2.89278197,
        5.30471303, 12.74748424,  5.01768709,  3.06028708, -0.38114381,
       16.04303583,  7.19527215,  9.89798935, 12.38424468,  0.36793359,
       10.75339907, 12.67315998, 10.37038602, 22.9711127 ,  9.93560993,
        2.12864522,  4.18390319,  4.48316369,  7.23573603,  3.1148749 ,
       -0.13647112, 16.35924503, 15.43796689, 10.1831074 ,  4.51893195,
       -0.47713093,  1.04266821, 11.70574985,  3.83948318,  1.17159881,
       13.25188896])

In [122]:
mae = mean_absolute_error(y_test,y_pred)

In [124]:
mae

1.37763981431796

In [126]:
score = r2_score(y_test,y_pred)

In [128]:
score

0.9430341365955304

In [132]:
#Ridge Regression
from sklearn.linear_model import Ridge

In [134]:
ridge = Ridge()

In [136]:
ridge.fit(x_train_scaled,y_train)

Ridge()

In [138]:
y_pred = ridge.predict(x_test_scaled)

In [140]:
y_pred

array([ 1.90978887e+01,  1.44468894e+01,  1.05187625e+00,  1.57218368e+01,
        6.81882220e+00,  4.69902581e+00,  7.77995548e+00,  1.68164411e+00,
        1.89405959e+00,  1.78304882e+00,  4.62287677e+00, -1.04720630e+00,
        6.34551796e+00, -1.12639282e+00,  6.99759329e-01,  4.76541107e-01,
        1.32221381e+00,  2.91075067e+01,  1.73169235e+01,  1.06124068e+01,
        2.12060943e+01,  2.13911231e+01,  5.16393103e+00,  1.08506765e+01,
        8.24107750e+00,  1.18453219e+01, -9.59578176e-01,  6.73918427e+00,
        2.27931455e+01,  1.35528703e+00,  4.13182123e+00,  1.43724205e+01,
        4.57419921e+00,  2.14099568e+00, -2.33121592e-01,  1.76029296e+01,
        6.66022852e+00,  1.07235289e+01,  1.31328862e+01, -1.55460395e-01,
        1.16927779e+01,  1.43301531e+01,  1.13511758e+01,  2.70050380e+01,
        9.98905577e+00,  1.07160148e+00,  4.30323609e+00,  2.75637088e+00,
        7.44648798e+00,  1.37115369e+00,  2.41016975e-04,  1.77979656e+01,
        1.68306442e+01,  

In [146]:
mae = mean_absolute_error(y_test,y_pred)

In [148]:
mae

0.7540689502639759

In [150]:
score = r2_score(y_test,y_pred)

In [152]:
score

0.9840151778801699

In [154]:
#Elastic Net Regression
from sklearn.linear_model import ElasticNet

In [156]:
elastic_net = ElasticNet()

In [158]:
elastic_net.fit(x_train_scaled,y_train)

ElasticNet()

In [162]:
y_pred = elastic_net.predict(x_test_scaled)

In [164]:
y_pred

array([15.29015223, 12.09215559,  2.77873945, 13.6364963 ,  7.41911682,
        6.06293512,  9.30498466,  3.38799099,  3.61747863,  3.42543021,
        6.04517417,  0.73742002,  7.88908438, -0.84942936,  3.07691618,
        2.86439169,  3.37709036, 21.5390806 , 14.95669351, 10.72795487,
       16.84004339, 16.74884899,  5.74690347, 10.05089871,  7.989968  ,
       11.22665605,  0.60354107,  7.4234864 , 18.17136268,  3.67532795,
        5.51359707, 12.02424207,  5.46626266,  3.21338287, -0.8636384 ,
       14.08418993,  7.68936681,  9.69709185, 12.07026686,  0.45540003,
       10.58205439, 12.16797449, 10.41841426, 20.00517629, 10.23629816,
        3.04924377,  5.66033543,  3.70634199,  7.45297961,  3.81413473,
       -0.41083154, 15.13186667, 14.37605427, 10.24314653,  3.96090697,
       -1.31056531,  1.00525389, 11.26411808,  4.28950006,  0.70095676,
       13.02142954])

In [166]:
y_test

83     20.3
76     16.1
61      0.8
181    13.5
106     5.9
       ... 
2       0.5
232    13.7
111     2.8
10      0.2
195    14.8
Name: FWI, Length: 61, dtype: float64

In [168]:
mae = mean_absolute_error(y_test,y_pred)

In [170]:
mae

2.077758954613436

In [172]:
score = r2_score(y_test,y_pred)

In [174]:
score

0.8752428346969718

In [176]:
import pickle
pickle.dump(scaler,open('scaler.pkl','wb'))
pickle.dump(ridge,open('ridge.pkl','wb'))